provendas/caixa/urls.py
# caixa/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.listar_caixa, name='listar_caixa'),
    path('abrir-caixa', views.abrir_caixa_pdv, name='abrir_caixa_pdv'),
    path('clients/search', views.search_client, name='search_client'),
    path('products/search', views.search_products, name='search_products'),
    
    path('finalizar_venda/', views.finalizar_venda, name='finalizar_venda'),
    path('finalizar_venda_multi/', views.finalizar_venda_multi, name='finalizar_venda_multi'),

    path('buscar/venda/<int:id>/', views.get_venda_details, name='admin.caixa.idVenda'),
    path('excluir_venda/', views.excluir_venda, name='excluir_venda'),
    path('cupom_fiscal/<int:pedido_id>/', views.gerar_cupom_fiscal, name='gerar_cupom_fiscal'),
    path('listar-pedidos-ajax/', views.listar_pedidos_ajax, name='listar_pedidos_ajax'),
    path('cupom_fiscal_ajax/<int:pedido_id>/', views.cupom_fiscal_ajax, name='cupom_fiscal_ajax'),
    
    path('abrir_caixa_ajax/', views.abrir_caixa_ajax, name='abrir_caixa_ajax'),
    path('fechar_caixa_ajax/', views.fechar_caixa_ajax, name='fechar_caixa_ajax'),
    path('verificar_caixa_aberto/', views.verificar_caixa_aberto, name='verificar_caixa_aberto'),

    # Ajax
    path('listar-caixas-abertos-ajax/', views.listar_caixas_abertos_ajax, name='listar_caixas_abertos_ajax'),
    path('retirar-ou-adicionar-valor-ajax/', views.retirar_ou_adicionar_valor_ajax, name='retirar_ou_adicionar_valor_ajax'),
    path('gerar-numero-pedido/', views.gerar_numero_unico, name='gerar_numero_pedido'),
    
    path('relatorio/', views.relatorio_caixa, name='relatorio_caixa'),
    path('relatorio/<int:caixa_id>/', views.carregar_dados_relatorio_caixa, name='carregar_dados_relatorio_caixa'),


    

]

provendas/configuracoes/urls.py
# configuracoes/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.listar_configuracao, name='listar_configuracao'),
    
]

provendas/provendas/urls.py
from django.conf import settings  # Certifique-se de importar as configurações
from django.conf.urls import handler404, handler403, handler500
from django.contrib import admin
from django.urls import path, include
from . import views
from django.views.generic import TemplateView
from django.conf.urls.static import static  # Importando para servir arquivos de mídia
from .views import login_view
from django.contrib.auth import views as auth_views




# Define suas views personalizadas
handler404 = TemplateView.as_view(template_name="404.html")
handler403 = TemplateView.as_view(template_name="403.html")
handler500 = TemplateView.as_view(template_name="500.html")


urlpatterns = [
    
    path('', views.home_redirect, name='home'),
    path('login/', login_view, name='login'),
    path('logout/', views.custom_logout, name='logout'),
    path('admin/', admin.site.urls),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('estoque/', include('estoque.urls')),
    path('empresas/', include('empresas.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('clientes/', include('clientes.urls')),
    path('caixa/', include('caixa.urls')),
    path('comanda/', include('comanda.urls')),
    path('configuracoes/', include('configuracoes.urls')),
    path('analytics/', include('analytics.urls')),
    path('licencas/', include('licencas.urls')),
]

# Adicione o suporte para arquivos de mídia
if settings.DEBUG:  # Apenas em modo de desenvolvimento
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

provendas/configuracoes/models.py
from django.db import models
from provendas.utils import caminho_upload


class Configuracao(models.Model):
    nome_aplicacao = models.CharField(max_length=100)
    cliente_padrao = models.ForeignKey(
        'clientes.Cliente', on_delete=models.SET_NULL, null=True, blank=True
    )
    cor_primaria = models.CharField(max_length=7, default="#16bb6e")
    cor_secundaria = models.CharField(max_length=7, default="#09ec41")  
    logo_empresa = models.ImageField(upload_to=caminho_upload, null=True, blank=True)
    icone_aplicacao = models.ImageField(upload_to=caminho_upload, null=True, blank=True)
    gerar_codigo_barra_automatico = models.BooleanField(default=False)
    gerenciar_abertura_fechamento_caixa = models.BooleanField(default=False)
    modoLeitorCodigoDeBarra = models.BooleanField(default=False)

    def __str__(self):
        return self.nome_aplicacao

provendas/configuracoes/forms.py
from django import forms
from .models import Configuracao
from clientes.models import Cliente  # Importando o modelo de Cliente

class ConfiguracaoForm(forms.ModelForm):
    class Meta:
        model = Configuracao
        fields = [
            'nome_aplicacao',
            'cliente_padrao',
            'cor_primaria',
            'cor_secundaria',
            'logo_empresa',
            'icone_aplicacao',
            'gerar_codigo_barra_automatico',  
            'gerenciar_abertura_fechamento_caixa', 
            'modoLeitorCodigoDeBarra',
        ]
        widgets = {
            'cliente_padrao': forms.Select(attrs={'class': 'form-control'}),
            'cor_primaria': forms.TextInput(attrs={'type': 'color', 'class': 'form-control'}),
            'cor_secundaria': forms.TextInput(attrs={'type': 'color', 'class': 'form-control'}),
            'nome_aplicacao': forms.TextInput(attrs={'class': 'form-control'}),
            'logo_empresa': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'icone_aplicacao': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            # Usando o Bootstrap Custom Checkbox
            'gerar_codigo_barra_automatico': forms.CheckboxInput(attrs={'class': 'custom-control-input'}),  
            'gerenciar_abertura_fechamento_caixa': forms.CheckboxInput(attrs={'class': 'custom-control-input'}),
            'modoLeitorCodigoDeBarra': forms.CheckboxInput(attrs={'class': 'custom-control-input'}),
        }

provendas/configuracoes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Configuracao
from .forms import ConfiguracaoForm

def listar_configuracao(request):
    # Obter ou criar a configuração
    configuracao, created = Configuracao.objects.get_or_create(id=1)

    if request.method == 'POST':
        form = ConfiguracaoForm(request.POST, request.FILES, instance=configuracao)
        if form.is_valid():
            form.save()

            return redirect('listar_configuracao')
    else:
        form = ConfiguracaoForm(instance=configuracao)

    # Passando os dados para a template para renderizar o formulário
    return render(request, 'configuracoes/listar_configuracao.html', {
        'form': form,
        'configuracao': configuracao
    })

provendas/templates/configuracoes/listar_configuracao.html
{% extends "template.html" %}

{% load static %}
{% block title %}
    Configurações
{% endblock %}

{% block content %}
<div class="wrapper">
    {% include 'includes/sidebar.html' %}
    {% include 'includes/navbar.html' %} 

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header py-3 shadow-sm">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="col-md-8">
                        <h1 class="font-weight-bold">
                            <i class="fas fa-chart-line"></i> Configurações da aplicação
                        </h1>
                    </div>
                    <div class="col-md-4 text-md-right">
                        
                    </div>
                </div>
            </div>
        </section>
        <section class="content py-3">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Lista de clientes</h3>
                            </div>
                            <div class="card-body">
                                <form method="POST" enctype="multipart/form-data">
                                    {% csrf_token %}
                
                                    <div class="row">
                                        <!-- Primeira Coluna -->
                                        <div class="col-md-6">
                                            <!-- Nome da Aplicação -->
                                            <div class="form-group">
                                                <h3 class="py-3">Dados da empresa</h3>
                                                <label for="id_nome_aplicacao" class="form-label">Nome da Aplicação</label>
                                                {{ form.nome_aplicacao }}
                                            </div>
                
                                            <!-- Logo da Empresa -->
                                            <div class="form-group">
                                                <label for="id_logo_empresa" class="form-label">Logo da Empresa</label>
                                                {{ form.logo_empresa }}
                                            </div>
                
                                            <!-- Ícone da Aplicação -->
                                            <div class="form-group">
                                                <label for="id_icone_aplicacao" class="form-label">Ícone da Aplicação</label>
                                                {{ form.icone_aplicacao }}
                                            </div>
                                        </div>
                
                                        <!-- Segunda Coluna -->
                                        <div class="col-md-6">
                                            <!-- Cores -->
                                            <div class="form-group">
                                                <h3 class="py-3">Cores da Aplicação</h3>
                                                <label for="id_cor_primaria" class="form-label">Cor Primária</label>
                                                {{ form.cor_primaria }}
                                            </div>
                                            
                                            <div class="form-group">
                                                <label for="id_cor_secundaria" class="form-label">Cor Secundária</label>
                                                {{ form.cor_secundaria }}
                                            </div>
                
                                            <!-- Cliente Padrão -->
                                            <div class="form-group">
                                                <h3 class="py-3">Configurações Cliente</h3>
                                                <label for="id_cliente_padrao" class="form-label">Cliente Padrão</label>
                                                {{ form.cliente_padrao }}
                                            </div>
                                        </div>
                                    </div>
                
                                    <!-- Outras Configurações em uma linha completa -->
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <h3 class="py-3">Comportamentos do estoque</h3>
                                                <label for="id_gerar_codigo_barra_automatico">Gerar Código de Barra Automático</label>
                                                <div class="custom-control custom-checkbox">
                                                    {{ form.gerar_codigo_barra_automatico }}
                                                    <label class="custom-control-label" for="id_gerar_codigo_barra_automatico">Ativar Geração Automática</label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <h3 class="py-3">Caixa</h3>
                                                <label for="id_gerenciar_abertura_fechamento_caixa">Gerenciar Abertura/Fechamento de Caixa</label>
                                                <div class="custom-control custom-checkbox">
                                                    {{ form.gerenciar_abertura_fechamento_caixa }}
                                                    <label class="custom-control-label" for="id_gerenciar_abertura_fechamento_caixa">Ativar Gerenciamento</label>
                                                </div>
                                            </div>
        
                                            <div class="form-group">
                                                <label for="id_modoLeitorCodigoDeBarra">Modo leitor de Código de Barras</label>
                                                <div class="custom-control custom-checkbox">
                                                    {{ form.modoLeitorCodigoDeBarra }}
                                                    <label class="custom-control-label" for="id_modoLeitorCodigoDeBarra">Ativar Modo Leitor</label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                
                                    <button type="submit" class="btn btn-success btn-sm w-100">Salvar Configurações Gerais</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        
        
        </div> 
            
</div>

{% block extra_scripts %}
    
{% endblock %}

{% endblock %}


                